"""remove carbon footprint prefix

Revision ID: f02a2525b97c
Revises: 551b2920b23c
Create Date: 2025-12-22 15:07:22.592366

"""
from typing import Sequence, Union
import logging

from alembic import op
from sqlalchemy.sql import table, column
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f02a2525b97c'
down_revision: Union[str, None] = '551b2920b23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
logger = logging.getLogger(__name__)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # create new columns (temporarily nullable) without the carbon_footprint prefix
    logger.warning("Adding new columns without carbon_footprint prefix...")
    op.add_column('provider', sa.Column('model_hosting_zone', sa.Enum('ABW', 'AFG', 'AGO', 'AIA', 'ALA', 'ALB', 'AND', 'ARE', 'ARG', 'ARM', 'ASM', 'ATA', 'ATF', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BES', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLM', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BVT', 'BWA', 'CAF', 'CAN', 'CCK', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COK', 'COL', 'COM', 'CPV', 'CRI', 'CUB', 'CUW', 'CXR', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU', 'EGY', 'ERI', 'ESH', 'ESP', 'EST', 'ETH', 'FIN', 'FJI', 'FLK', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GGY', 'GHA', 'GIB', 'GIN', 'GLP', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUF', 'GUM', 'GUY', 'HKG', 'HMD', 'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IMN', 'IND', 'IOT', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JEY', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LIE', 'LKA', 'LSO', 'LTU', 'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEX', 'MHL', 'MKD', 'MLI', 'MLT', 'MMR', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MSR', 'MTQ', 'MUS', 'MWI', 'MYS', 'MYT', 'NAM', 'NCL', 'NER', 'NFK', 'NGA', 'NIC', 'NIU', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OMN', 'PAK', 'PAN', 'PCN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PYF', 'QAT', 'REU', 'ROU', 'RUS', 'RWA', 'SAU', 'SDN', 'SEN', 'SGP', 'SGS', 'SHN', 'SJM', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SPM', 'SRB', 'SSD', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TGO', 'THA', 'TJK', 'TKL', 'TKM', 'TLS', 'TON', 'TTO', 'TUN', 'TUR', 'TUV', 'TWN', 'TZA', 'UGA', 'UKR', 'UMI', 'URY', 'USA', 'UZB', 'VAT', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLF', 'WOR', 'WSM', 'YEM', 'ZAF', 'ZMB', 'ZWE', name='providercarbonfootprintzone'), nullable=True))
    op.add_column('provider', sa.Column('model_total_params', sa.Integer(), nullable=True))
    op.add_column('provider', sa.Column('model_active_params', sa.Integer(), nullable=True))
    logger.warning("Adding new columns without carbon_footprint prefix... Done.")

    # copy previous data into the newly created columns
    logger.warning("Copying data from old columns to new columns...")
    op.execute(
        "UPDATE provider SET "
        "model_total_params = model_carbon_footprint_total_params, "
        "model_active_params = model_carbon_footprint_active_params, "
        "model_hosting_zone = model_carbon_footprint_zone"
    )
    logger.warning("Copying data from old columns to new columns... Done.")


    # check for NULL values before making columns non-nullable
    logger.warning("Checking for NULL values in new columns, this operation may abort the migration if any are found...")
    provider = table(
        "provider",
        column("model_total_params", sa.String),
        column("model_active_params", sa.String),
    )
    result = op.get_bind().execute(
        sa.select(sa.func.count())
        .select_from(provider)
        .where(
            sa.or_(
                provider.c.model_total_params.is_(None),
                provider.c.model_active_params.is_(None),
            )
        )
    ).scalar()

    if result > 0:
        raise ValueError(
            "Some NULL values are found in model_total_params or model_active_params columns. Migration aborted, please review your data.")
    logger.warning("Checking for NULL values in new columns, this operation may abort the migration if any are found... Done.")
    logger.warning("Check passed. No NULL values found in old columns.")

    # make the new columns non-nullable
    logger.warning("Making new columns non-nullable...")
    op.alter_column('provider', 'model_total_params', nullable=False)
    op.alter_column('provider', 'model_active_params', nullable=False)
    logger.warning("Making new columns non-nullable... Done.")

    # drop the old columns
    logger.warning("Dropping old columns with carbon_footprint prefix...")
    op.drop_column('provider', 'model_carbon_footprint_total_params')
    op.drop_column('provider', 'model_carbon_footprint_zone')
    op.drop_column('provider', 'model_carbon_footprint_active_params')
    logger.warning("Dropping old columns with carbon_footprint prefix... Done.")

    logger.warning("Migration completed successfully.")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # re-create old columns (temporarily nullable)
    logger.warning("Adding old columns with carbon_footprint prefix...")
    op.add_column('provider', sa.Column('model_carbon_footprint_zone', postgresql.ENUM('ABW', 'AFG', 'AGO', 'AIA', 'ALA', 'ALB', 'AND', 'ARE', 'ARG', 'ARM', 'ASM', 'ATA', 'ATF', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BES', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLM', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BVT', 'BWA', 'CAF', 'CAN', 'CCK', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COK', 'COL', 'COM', 'CPV', 'CRI', 'CUB', 'CUW', 'CXR', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU', 'EGY', 'ERI', 'ESH', 'ESP', 'EST', 'ETH', 'FIN', 'FJI', 'FLK', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GGY', 'GHA', 'GIB', 'GIN', 'GLP', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUF', 'GUM', 'GUY', 'HKG', 'HMD', 'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IMN', 'IND', 'IOT', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JEY', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LIE', 'LKA', 'LSO', 'LTU', 'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEX', 'MHL', 'MKD', 'MLI', 'MLT', 'MMR', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MSR', 'MTQ', 'MUS', 'MWI', 'MYS', 'MYT', 'NAM', 'NCL', 'NER', 'NFK', 'NGA', 'NIC', 'NIU', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OMN', 'PAK', 'PAN', 'PCN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PYF', 'QAT', 'REU', 'ROU', 'RUS', 'RWA', 'SAU', 'SDN', 'SEN', 'SGP', 'SGS', 'SHN', 'SJM', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SPM', 'SRB', 'SSD', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TGO', 'THA', 'TJK', 'TKL', 'TKM', 'TLS', 'TON', 'TTO', 'TUN', 'TUR', 'TUV', 'TWN', 'TZA', 'UGA', 'UKR', 'UMI', 'URY', 'USA', 'UZB', 'VAT', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLF', 'WOR', 'WSM', 'YEM', 'ZAF', 'ZMB', 'ZWE', name='providercarbonfootprintzone'), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('model_carbon_footprint_active_params', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('model_carbon_footprint_total_params', sa.INTEGER(), autoincrement=False, nullable=True))
    logger.warning("Adding old columns with carbon_footprint prefix... Done.")

    # copy data back into old columns
    logger.warning("Copying data from new columns back to old columns...")
    op.execute(
        "UPDATE provider SET "
        "model_carbon_footprint_total_params = model_total_params, "
        "model_carbon_footprint_active_params = model_active_params, "
        "model_carbon_footprint_zone = model_hosting_zone"
    )
    logger.warning("Copying data from new columns back to old columns... Done.")

    # check for NULL values before making columns non-nullable
    logger.warning("Checking for NULL values in restored columns, this operation may abort the downgrade if any are found...")
    provider = table(
        "provider",
        column("model_carbon_footprint_total_params", sa.Integer),
        column("model_carbon_footprint_active_params", sa.Integer),
    )
    result = op.get_bind().execute(
        sa.select(sa.func.count())
        .select_from(provider)
        .where(
            sa.or_(
                provider.c.model_carbon_footprint_total_params.is_(None),
                provider.c.model_carbon_footprint_active_params.is_(None),
            )
        )
    ).scalar()

    if result > 0:
        raise ValueError(
            "Some NULL values are found in model_carbon_footprint_total_params or model_carbon_footprint_active_params columns. Downgrade aborted.")
    logger.warning("Checking for NULL values in restored columns, this operation may abort the downgrade if any are found... Done.")
    logger.warning("Check passed. No NULL values found in restored columns.")

    # make the restored columns non-nullable
    logger.warning("Making restored columns non-nullable...")
    op.alter_column('provider', 'model_carbon_footprint_total_params', nullable=False)
    op.alter_column('provider', 'model_carbon_footprint_active_params', nullable=False)
    logger.warning("Making restored columns non-nullable... Done.")

    # drop the prefixed columns
    logger.warning("Dropping new columns without carbon_footprint prefix...")
    op.drop_column('provider', 'model_active_params')
    op.drop_column('provider', 'model_total_params')
    op.drop_column('provider', 'model_hosting_zone')
    logger.warning("Dropping new columns without carbon_footprint prefix... Done.")

    logger.warning("Downgrade completed successfully.")
    # ### end Alembic commands ###
