"""add_image_to_text_model_type

Revision ID: 9b3cdc1e64dd
Revises: 843230e94aec
Create Date: 2025-12-09 18:58:02.853520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3cdc1e64dd'
down_revision: Union[str, None] = '843230e94aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE modeltype ADD VALUE IF NOT EXISTS 'IMAGE_TO_TEXT';")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

