"""refacto model provision

Revision ID: 9ba1f6a21f20
Revises: a1b2c3d4e5f6
Create Date: 2025-11-13 20:12:18.714704

"""
from typing import Sequence, Union
import logging

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision: str = '9ba1f6a21f20'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('router',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE_TEXT_TO_TEXT', 'AUTOMATIC_SPEECH_RECOGNITION', 'TEXT_EMBEDDINGS_INFERENCE', 'TEXT_GENERATION', 'TEXT_CLASSIFICATION', name='modeltype'), nullable=False),
    sa.Column('load_balancing_strategy', sa.Enum('SHUFFLE', 'LEAST_BUSY', name='routerloadbalancingstrategy'), nullable=False),
    sa.Column('cost_prompt_tokens', sa.Float(), nullable=False),
    sa.Column('cost_completion_tokens', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.Column('updated', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_router_id'), 'router', ['id'], unique=False)
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('ALBERT', 'OPENAI', 'TEI', 'VLLM', name='providertype'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_carbon_footprint_zone', sa.Enum('ABW', 'AFG', 'AGO', 'AIA', 'ALA', 'ALB', 'AND', 'ARE', 'ARG', 'ARM', 'ASM', 'ATA', 'ATF', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BES', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLM', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BVT', 'BWA', 'CAF', 'CAN', 'CCK', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COK', 'COL', 'COM', 'CPV', 'CRI', 'CUB', 'CUW', 'CXR', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU', 'EGY', 'ERI', 'ESH', 'ESP', 'EST', 'ETH', 'FIN', 'FJI', 'FLK', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GGY', 'GHA', 'GIB', 'GIN', 'GLP', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUF', 'GUM', 'GUY', 'HKG', 'HMD', 'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IMN', 'IND', 'IOT', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JEY', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LIE', 'LKA', 'LSO', 'LTU', 'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEX', 'MHL', 'MKD', 'MLI', 'MLT', 'MMR', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MSR', 'MTQ', 'MUS', 'MWI', 'MYS', 'MYT', 'NAM', 'NCL', 'NER', 'NFK', 'NGA', 'NIC', 'NIU', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OMN', 'PAK', 'PAN', 'PCN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PYF', 'QAT', 'REU', 'ROU', 'RUS', 'RWA', 'SAU', 'SDN', 'SEN', 'SGP', 'SGS', 'SHN', 'SJM', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SPM', 'SRB', 'SSD', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TGO', 'THA', 'TJK', 'TKL', 'TKM', 'TLS', 'TON', 'TTO', 'TUN', 'TUR', 'TUV', 'TWN', 'TZA', 'UGA', 'UKR', 'UMI', 'URY', 'USA', 'UZB', 'VAT', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLF', 'WOR', 'WSM', 'YEM', 'ZAF', 'ZMB', 'ZWE', name='providercarbonfootprintzone'), nullable=True),
    sa.Column('model_carbon_footprint_total_params', sa.Integer(), nullable=True),
    sa.Column('model_carbon_footprint_active_params', sa.Integer(), nullable=True),
    sa.Column('qos_metric', sa.Enum('TTFT', 'LATENCY', 'INFLIGHT', 'PERFORMANCE', name='metric'), nullable=True),
    sa.Column('qos_value', sa.Float(), nullable=True),
    sa.Column('max_context_length', sa.Integer(), nullable=True),
    sa.Column('vector_size', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.Column('updated', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['router_id'], ['router.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'model_name', name='unique_provider_url_model_name')
    )
    op.create_index(op.f('ix_provider_id'), 'provider', ['id'], unique=False)
    op.create_table('router_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['router_id'], ['router.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_router_alias_id'), 'router_alias', ['id'], unique=False)
    # Drop tables that depend on 'model' first, before dropping 'model' itself
    op.drop_index(op.f('ix_model_alias_id'), table_name='model_alias')
    op.drop_table('model_alias')
    op.drop_index(op.f('ix_model_client_id'), table_name='model_client')
    op.drop_table('model_client')
    op.drop_index(op.f('ix_model_name'), table_name='model')
    op.drop_table('model')
    op.add_column('collection', sa.Column('created', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('collection', sa.Column('updated', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.drop_column('collection', 'created_at')
    op.drop_column('collection', 'updated_at')
    op.add_column('document', sa.Column('created', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.drop_column('document', 'created_at')
    logger.warning("Clearing all existing data from 'limit' table due to incompatible schema changes (model -> router_id)")
    op.execute('DELETE FROM "limit"')

    op.add_column('limit', sa.Column('router_id', sa.Integer(), nullable=False))
    op.add_column('limit', sa.Column('created', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.drop_index(op.f('ix_limit_id'), table_name='limit')
    op.drop_constraint(op.f('unique_rate_limit_per_role'), 'limit', type_='unique')
    op.create_unique_constraint('unique_rate_limit_per_role', 'limit', ['role_id', 'router_id', 'type'])
    op.create_foreign_key(None, 'limit', 'router', ['router_id'], ['id'], ondelete='CASCADE')
    op.drop_column('limit', 'created_at')
    op.drop_column('limit', 'model')
    op.add_column('organization', sa.Column('created', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('organization', sa.Column('updated', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.drop_column('organization', 'created_at')
    op.drop_column('organization', 'updated_at')

    # Clear the permission table before schema changes
    logger.warning("Clearing all existing data from 'permission' table due to schema changes")
    op.execute('DELETE FROM "permission"')
    
    op.add_column('permission', sa.Column('created', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_column('permission', 'created_at')
    op.add_column('role', sa.Column('created', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('role', sa.Column('updated', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_column('role', 'created_at')
    op.drop_column('role', 'updated_at')
    op.add_column('token', sa.Column('expires', sa.DateTime(), nullable=True))
    op.add_column('token', sa.Column('created', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.drop_column('token', 'created_at')
    op.drop_column('token', 'expires_at')
    op.add_column('usage', sa.Column('router_id', sa.Integer(), nullable=True))
    op.add_column('usage', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.add_column('usage', sa.Column('user_email', sa.String(), nullable=True))
    op.add_column('usage', sa.Column('token_name', sa.String(), nullable=True))
    op.add_column('usage', sa.Column('router_name', sa.String(), nullable=True))
    op.add_column('usage', sa.Column('provider_model_name', sa.String(), nullable=True))
    op.drop_constraint(op.f('usage_user_id_fkey'), 'usage', type_='foreignkey')
    op.create_foreign_key(None, 'usage', 'router', ['router_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'usage', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'usage', 'provider', ['provider_id'], ['id'], ondelete='SET NULL')

    # Migrate data before dropping columns
    # Copy request_model -> router_name
    op.execute("""
        UPDATE usage
        SET router_name = request_model
        WHERE request_model IS NOT NULL
    """)
    
    # Copy model -> provider_model_name
    op.execute("""
        UPDATE usage
        SET provider_model_name = model
        WHERE model IS NOT NULL
    """)
    
    # Complete user_email from user table
    op.execute("""
        UPDATE usage
        SET user_email = u.email
        FROM "user" u
        WHERE usage.user_id = u.id
        AND usage.user_email IS NULL
    """)
    
    # Complete token_name from token table
    op.execute("""
        UPDATE usage
        SET token_name = t.name
        FROM token t
        WHERE usage.token_id = t.id
        AND usage.token_name IS NULL
    """)
    
    # Complete router_name from router table (if not already set from request_model)
    op.execute("""
        UPDATE usage
        SET router_name = r.name
        FROM router r
        WHERE usage.router_id = r.id
        AND usage.router_name IS NULL
    """)
    
    # Complete provider_model_name from provider table (if not already set from model)
    op.execute("""
        UPDATE usage
        SET provider_model_name = p.model_name
        FROM provider p
        WHERE usage.provider_id = p.id
        AND usage.provider_model_name IS NULL
    """)

    op.drop_column('usage', 'model')
    op.drop_column('usage', 'request_model')
    op.add_column('user', sa.Column('expires', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('user', sa.Column('updated', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_unique_constraint('unique_user_id_organization_id', 'user', ['id', 'organization_id'])
    op.drop_constraint(op.f('user_organization_id_fkey'), 'user', type_='foreignkey')
    op.drop_constraint(op.f('user_role_id_fkey'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'organization', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'expires_at')
    op.drop_column('user', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_role_id_fkey'), 'user', 'role', ['role_id'], ['id'])
    op.create_foreign_key(op.f('user_organization_id_fkey'), 'user', 'organization', ['organization_id'], ['id'])
    op.drop_constraint('unique_user_id_organization_id', 'user', type_='unique')
    op.drop_column('user', 'updated')
    op.drop_column('user', 'created')
    op.drop_column('user', 'expires')
    op.add_column('usage', sa.Column('request_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usage', type_='foreignkey')
    op.drop_constraint(None, 'usage', type_='foreignkey')
    op.drop_constraint(None, 'usage', type_='foreignkey')
    op.create_foreign_key(op.f('usage_user_id_fkey'), 'usage', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('usage', 'provider_model_name')
    op.drop_column('usage', 'router_name')
    op.drop_column('usage', 'token_name')
    op.drop_column('usage', 'user_email')
    op.drop_column('usage', 'provider_id')
    op.drop_column('usage', 'router_id')
    op.add_column('token', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('token', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('token', 'created')
    op.drop_column('token', 'expires')
    op.add_column('role', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('role', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.drop_column('role', 'updated')
    op.drop_column('role', 'created')
    op.add_column('permission', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.drop_column('permission', 'created')
    op.add_column('organization', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('organization', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('organization', 'updated')
    op.drop_column('organization', 'created')
    op.add_column('limit', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('limit', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'limit', type_='foreignkey')
    op.drop_constraint('unique_rate_limit_per_role', 'limit', type_='unique')
    op.create_unique_constraint(op.f('unique_rate_limit_per_role'), 'limit', ['role_id', 'model', 'type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_limit_id'), 'limit', ['id'], unique=False)
    op.drop_column('limit', 'created')
    op.drop_column('limit', 'router_id')
    op.add_column('document', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('document', 'created')
    op.add_column('collection', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('collection', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('collection', 'updated')
    op.drop_column('collection', 'created')
    op.create_table('model_client',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timeout', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_cost_prompt_tokens', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_cost_completion_tokens', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_carbon_footprint_zone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_carbon_footprint_total_params', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_carbon_footprint_active_params', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_router_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qos_policy', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('performance_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_parallel_requests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_router_name'], ['model.name'], name=op.f('model_client_model_router_name_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('model_client_pkey'))
    )
    op.create_index(op.f('ix_model_client_id'), 'model_client', ['id'], unique=False)
    op.create_table('model',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('routing_strategy', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owned_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vector_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_context_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_config', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cycle_offset', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='model_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_model_name'), 'model', ['name'], unique=False)
    op.create_table('model_alias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_router_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['model_router_name'], ['model.name'], name=op.f('model_alias_model_router_name_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('model_alias_pkey'))
    )
    op.create_index(op.f('ix_model_alias_id'), 'model_alias', ['id'], unique=False)
    op.drop_index(op.f('ix_router_alias_id'), table_name='router_alias')
    op.drop_table('router_alias')
    op.drop_index(op.f('ix_provider_id'), table_name='provider')
    op.drop_table('provider')
    op.drop_index(op.f('ix_router_id'), table_name='router')
    op.drop_table('router')
    # ### end Alembic commands ###
