"""add mistral type

Revision ID: 0ae7dc72ec5c
Revises: 85459163c680
Create Date: 2025-11-19 11:20:50.116057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae7dc72ec5c'
down_revision: Union[str, None] = '85459163c680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE providertype ADD VALUE IF NOT EXISTS 'MISTRAL';")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
