"""add index to usage

Revision ID: 05211e3047e8
Revises: 9ba1f6a21f20
Create Date: 2025-11-13 21:52:43.773956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05211e3047e8'
down_revision: Union[str, None] = '9ba1f6a21f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usage_provider_id'), 'usage', ['provider_id'], unique=False)
    op.create_index(op.f('ix_usage_router_id'), 'usage', ['router_id'], unique=False)
    op.create_index(op.f('ix_usage_token_id'), 'usage', ['token_id'], unique=False)
    op.create_index(op.f('ix_usage_user_id'), 'usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_user_id'), table_name='usage')
    op.drop_index(op.f('ix_usage_token_id'), table_name='usage')
    op.drop_index(op.f('ix_usage_router_id'), table_name='usage')
    op.drop_index(op.f('ix_usage_provider_id'), table_name='usage')
    # ### end Alembic commands ###
