"""Move user auth from ui to app

Revision ID: 788a3b052a11
Revises: c1e54102255e
Create Date: 2025-08-22 11:57:50.150602

"""

import logging
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData, Table, create_engine
from sqlalchemy import select as sa_select

from api.utils.configuration import configuration

logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision: str = "788a3b052a11"
down_revision: Union[str, None] = "c1e54102255e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(), nullable=True))
    # ### end Alembic commands ###

    if not hasattr(configuration, "playground"):
        logging.warning("Playground configuration not found in the config file; skipping user password migration")
        return

    if not hasattr(configuration.playground, "postgres"):
        logging.warning("Playground configuration not found in the config file; skipping user password migration")
        return

    if configuration.playground.postgres == {}:
        logging.warning("Playground database url not set in the config file to migrate user passwords; skipping user password migration")
        return

    playground_url = configuration.playground.postgres.get("url").replace("+asyncpg", "")
    if not playground_url:
        logging.warning("Playground database url not set in the config file to migrate user passwords; skipping user password migration")
        return

    # Create an engine to the playground DB and reflect its `user` table
    pg_engine = create_engine(playground_url)
    pg_meta = MetaData()
    pg_meta.reflect(bind=pg_engine)

    if "user" not in pg_meta.tables:
        pg_engine.dispose()
        logging.warning("No `user` table found in playground DB; skipping user password migration")
        return

    pg_user = Table("user", pg_meta, autoload_with=pg_engine)

    # Use the current Alembic/app bind to update the new password column
    bind = op.get_bind()
    api_pg_meta = MetaData()
    api_pg_meta.reflect(bind=bind)
    if "user" not in api_pg_meta.tables:
        pg_engine.dispose()
        raise RuntimeError("No `user` table found in app DB")

    api_user = Table("user", api_pg_meta, autoload_with=bind)

    copied = 0
    with pg_engine.connect() as pg_conn:
        stmt = sa_select(pg_user.c.api_user_id, getattr(pg_user.c, "password"))
        result = pg_conn.execute(stmt)
        for row in result:
            api_user_id = row[0]
            pwd = row[1]
            if pwd is None:
                continue
            upd = api_user.update().where(api_user.c.id == api_user_id).values(password=pwd)
            bind.execute(upd)
            copied += 1

    pg_engine.dispose()
    logger.info(f"alembic: copied {copied} user passwords from playground DB to app DB")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###
