"""rename qos_value to qos_limit

Revision ID: 85459163c680
Revises: 05211e3047e8
Create Date: 2025-11-14 16:42:34.727148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85459163c680'
down_revision: Union[str, None] = '05211e3047e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE permissiontype ADD VALUE IF NOT EXISTS 'PROVIDE_MODELS';")

    op.add_column('provider', sa.Column('qos_limit', sa.Float(), nullable=True))
    op.drop_column('provider', 'qos_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('qos_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('provider', 'qos_limit')
    # ### end Alembic commands ###
