"""add unique constraint on organization name column

Revision ID: 2d2550e0771d
Revises: 9b3cdc1e64dd
Create Date: 2025-12-11 10:10:32.502840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import logging


# revision identifiers, used by Alembic.
revision: str = '2d2550e0771d'
down_revision: Union[str, None] = '9b3cdc1e64dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
logger = logging.getLogger(__name__)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    logger.warning("WARNING: Adding unique constraint on organization name.")
    logger.warning("WARNING: The following operation may fail if there are duplicate organization names in the database.")
    op.create_unique_constraint(None, 'organization', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='unique')
    # ### end Alembic commands ###
