"""remove_min_max_carbon_impact

Revision ID: c206a2bfefe9
Revises: f02a2525b97c
Create Date: 2026-02-26 17:30:35.635658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c206a2bfefe9'
down_revision: Union[str, None] = 'f02a2525b97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('kwh', sa.Float(), nullable=True))
    op.add_column('usage', sa.Column('kgco2eq', sa.Float(), nullable=True))
    op.drop_column('usage', 'kgco2eq_max')
    op.drop_column('usage', 'kwh_min')
    op.drop_column('usage', 'kgco2eq_min')
    op.drop_column('usage', 'kwh_max')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('kwh_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('kgco2eq_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('kwh_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('kgco2eq_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('usage', 'kgco2eq')
    op.drop_column('usage', 'kwh')
    # ### end Alembic commands ###
