name: opengatellm-ci

services:
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    restart: always
    env_file: "${APP_ENV_FILE:-.env.ci}"
    ports:
      - 8080:8080
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: ..
      dockerfile: api/Dockerfile
    command: ["celery", "-A", "api.tasks.celery_app.celery_app", "worker", "-Q", "model.default,model.albert-large,model.albert-small,model.embeddings-small,model.audio-large,model.rerank-small,model.testbed", "-l", "info"]
    env_file: "${APP_ENV_FILE:-.env.ci}"
    volumes:
      - "../api/tests/integ/config.test.yml:/config.yml:ro"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  postgres:
    extends:
      file: ../compose.example.yml
      service: postgres

  redis:
    extends:
      file: ../compose.example.yml
      service: redis

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    restart: always
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "ELASTIC_USERNAME=${ELASTICSEARCH_USER:-elastic}"
      - "ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "bash", "-c", ":> /dev/tcp/127.0.0.1/9200" ]
      interval: 4s
      timeout: 10s
      retries: 5

volumes:
  postgres:
  redis:
  elasticsearch: