name: opengatellm-ci

services:
  worker:
    build:
      context: ..
      dockerfile: api/Dockerfile
      target: worker
    volumes:
      - "../api/tests/integ/config.test.yml:/config.yml:ro"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  postgres:
    extends:
      file: ../compose.example.yml
      service: postgres

  redis:
    extends:
      file: ../compose.example.yml
      service: redis

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    ports:
      - "15672:15672"
      - "${RABBITMQ_PORT:-5672}:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-rabbitmq}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping && rabbitmqctl -q status"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    restart: always
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "ELASTIC_USERNAME=${ELASTICSEARCH_USER:-elasticsearch}"
      - "ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "bash", "-c", ":> /dev/tcp/127.0.0.1/9200" ]
      interval: 4s
      timeout: 10s
      retries: 5

volumes:
  postgres:
  redis:
  elasticsearch:
