"""Move user auth from ui to app

Revision ID: 788a3b052a11
Revises: c1e54102255e
Create Date: 2025-08-22 11:57:50.150602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import create_engine, MetaData, Table, select as sa_select
from app.utils.configuration import configuration


# revision identifiers, used by Alembic.
revision: str = "788a3b052a11"
down_revision: Union[str, None] = "c1e54102255e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(), nullable=True))
    # ### end Alembic commands ###

    playground_url = configuration.playground.postgres.get("url").replace("+asyncpg", "")
    if not playground_url:
        raise RuntimeError("Playground database url not set in the config file to migrate user passwords")

    # Create an engine to the playground DB and reflect its `user` table
    pg_engine = create_engine(playground_url)
    pg_meta = MetaData()
    pg_meta.reflect(bind=pg_engine, only=["user"])  # reflect user table only
    if "user" not in pg_meta.tables:
        pg_engine.dispose()
        raise RuntimeError("No `user` table found in playground DB")

    pg_user = Table("user", pg_meta, autoload_with=pg_engine)

    # Use the current Alembic/app bind to update the new password column
    bind = op.get_bind()
    app_meta = MetaData()
    app_meta.reflect(bind=bind, only=["user"])  # reflect app user table
    if "user" not in app_meta.tables:
        pg_engine.dispose()
        raise RuntimeError("No `user` table found in app DB")

    app_user = Table("user", app_meta, autoload_with=bind)

    copied = 0
    with pg_engine.connect() as pg_conn:
        stmt = sa_select(pg_user.c.id, getattr(pg_user.c, "password"))
        result = pg_conn.execute(stmt)
        for row in result:
            user_id = row[0]
            pwd = row[1]
            if pwd is None:
                continue
            upd = app_user.update().where(app_user.c.id == user_id).values(password=pwd)
            bind.execute(upd)
            copied += 1

    pg_engine.dispose()
    print(f"alembic: copied {copied} user passwords from playground DB to app DB")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###
