"""add identifier in usage

Revision ID: a2aec4bfd675
Revises: ea462f747600
Create Date: 2025-11-13 13:55:38.815044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2aec4bfd675'
down_revision: Union[str, None] = 'ea462f747600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use existing ENUM types (created in previous migration) without recreating them
    metrictype_enum = postgresql.ENUM('TTFT', 'LATENCY', 'INFLIGHT', 'PERFORMANCE', name='metrictype', create_type=False)
    providertype_enum = postgresql.ENUM('ALBERT', 'OPENAI', 'TEI', 'VLLM', name='providertype', create_type=False)
    providercarbonfootprintzone_enum = postgresql.ENUM('ABW', 'AFG', 'AGO', 'AIA', 'ALA', 'ALB', 'AND', 'ARE', 'ARG', 'ARM', 'ASM', 'ATA', 'ATF', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BES', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLM', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BVT', 'BWA', 'CAF', 'CAN', 'CCK', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COK', 'COL', 'COM', 'CPV', 'CRI', 'CUB', 'CUW', 'CXR', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU', 'EGY', 'ERI', 'ESH', 'ESP', 'EST', 'ETH', 'FIN', 'FJI', 'FLK', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GGY', 'GHA', 'GIB', 'GIN', 'GLP', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUF', 'GUM', 'GUY', 'HKG', 'HMD', 'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IMN', 'IND', 'IOT', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JEY', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LIE', 'LKA', 'LSO', 'LTU', 'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEX', 'MHL', 'MKD', 'MLI', 'MLT', 'MMR', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MSR', 'MTQ', 'MUS', 'MWI', 'MYS', 'MYT', 'NAM', 'NCL', 'NER', 'NFK', 'NGA', 'NIC', 'NIU', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OMN', 'PAK', 'PAN', 'PCN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PYF', 'QAT', 'REU', 'ROU', 'RUS', 'RWA', 'SAU', 'SDN', 'SEN', 'SGP', 'SGS', 'SHN', 'SJM', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SPM', 'SRB', 'SSD', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TGO', 'THA', 'TJK', 'TKL', 'TKM', 'TLS', 'TON', 'TTO', 'TUN', 'TUR', 'TUV', 'TWN', 'TZA', 'UGA', 'UKR', 'UMI', 'URY', 'USA', 'UZB', 'VAT', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLF', 'WOR', 'WSM', 'YEM', 'ZAF', 'ZMB', 'ZWE', name='providercarbonfootprintzone', create_type=False)
    
    # Drop router_provider table first to avoid constraint name conflict
    op.drop_index(op.f('ix_router_provider_id'), table_name='router_provider')
    op.drop_table('router_provider')
    
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', providertype_enum, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_carbon_footprint_zone', providercarbonfootprintzone_enum, nullable=True),
    sa.Column('model_carbon_footprint_total_params', sa.Integer(), nullable=True),
    sa.Column('model_carbon_footprint_active_params', sa.Integer(), nullable=True),
    sa.Column('qos_metric', metrictype_enum, nullable=True),
    sa.Column('qos_value', sa.Float(), nullable=True),
    sa.Column('max_context_length', sa.Integer(), nullable=True),
    sa.Column('vector_size', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['router_id'], ['router.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'model_name', name='unique_provider_url_model_name')
    )
    op.create_index(op.f('ix_provider_id'), 'provider', ['id'], unique=False)
    op.add_column('token', sa.Column('expires', sa.DateTime(), nullable=True))
    op.drop_column('token', 'expires_at')
    op.add_column('usage', sa.Column('router_id', sa.Integer(), nullable=True))
    op.add_column('usage', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.add_column('usage', sa.Column('user_email', sa.String(), nullable=True))
    op.add_column('usage', sa.Column('token_name', sa.String(), nullable=True))
    op.add_column('usage', sa.Column('router_name', sa.String(), nullable=True))
    op.add_column('usage', sa.Column('provider_model_name', sa.String(), nullable=True))
    op.add_column('usage', sa.Column('latency', sa.Integer(), nullable=True))
    op.add_column('usage', sa.Column('ttft', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usage', 'provider', ['provider_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'usage', 'router', ['router_id'], ['id'], ondelete='SET NULL')
    
    # Migrate data before dropping columns
    # Copy request_model -> router_name
    op.execute("""
        UPDATE usage
        SET router_name = request_model
        WHERE request_model IS NOT NULL
    """)
    
    # Copy model -> provider_model_name
    op.execute("""
        UPDATE usage
        SET provider_model_name = model
        WHERE model IS NOT NULL
    """)
    
    # Copy duration -> latency
    op.execute("""
        UPDATE usage
        SET latency = duration
        WHERE duration IS NOT NULL
    """)
    
    # Copy time_to_first_token -> ttft
    op.execute("""
        UPDATE usage
        SET ttft = time_to_first_token
        WHERE time_to_first_token IS NOT NULL
    """)
    
    # Complete user_email from user table
    op.execute("""
        UPDATE usage
        SET user_email = u.email
        FROM "user" u
        WHERE usage.user_id = u.id
        AND usage.user_email IS NULL
    """)
    
    # Complete token_name from token table
    op.execute("""
        UPDATE usage
        SET token_name = t.name
        FROM token t
        WHERE usage.token_id = t.id
        AND usage.token_name IS NULL
    """)
    
    # Complete router_name from router table (if not already set from request_model)
    op.execute("""
        UPDATE usage
        SET router_name = r.name
        FROM router r
        WHERE usage.router_id = r.id
        AND usage.router_name IS NULL
    """)
    
    # Complete provider_model_name from provider table (if not already set from model)
    op.execute("""
        UPDATE usage
        SET provider_model_name = p.model_name
        FROM provider p
        WHERE usage.provider_id = p.id
        AND usage.provider_model_name IS NULL
    """)
    
    # Now drop the old columns
    op.drop_column('usage', 'request_model')
    op.drop_column('usage', 'duration')
    op.drop_column('usage', 'time_to_first_token')
    op.drop_column('usage', 'model')
    op.add_column('user', sa.Column('expires', sa.DateTime(), nullable=True))
    op.drop_column('user', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'expires')
    op.add_column('usage', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('time_to_first_token', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('request_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usage', type_='foreignkey')
    op.drop_constraint(None, 'usage', type_='foreignkey')
    op.drop_column('usage', 'ttft')
    op.drop_column('usage', 'latency')
    op.drop_column('usage', 'provider_model_name')
    op.drop_column('usage', 'router_name')
    op.drop_column('usage', 'token_name')
    op.drop_column('usage', 'user_email')
    op.drop_column('usage', 'provider_id')
    op.drop_column('usage', 'router_id')
    op.add_column('token', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('token', 'expires')
    op.create_table('router_provider',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('router_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('ALBERT', 'OPENAI', 'TEI', 'VLLM', name='providertype'), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timeout', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_carbon_footprint_zone', postgresql.ENUM('ABW', 'AFG', 'AGO', 'AIA', 'ALA', 'ALB', 'AND', 'ARE', 'ARG', 'ARM', 'ASM', 'ATA', 'ATF', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BES', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLM', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BVT', 'BWA', 'CAF', 'CAN', 'CCK', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COK', 'COL', 'COM', 'CPV', 'CRI', 'CUB', 'CUW', 'CXR', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU', 'EGY', 'ERI', 'ESH', 'ESP', 'EST', 'ETH', 'FIN', 'FJI', 'FLK', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GGY', 'GHA', 'GIB', 'GIN', 'GLP', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUF', 'GUM', 'GUY', 'HKG', 'HMD', 'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IMN', 'IND', 'IOT', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JEY', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LIE', 'LKA', 'LSO', 'LTU', 'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEX', 'MHL', 'MKD', 'MLI', 'MLT', 'MMR', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MSR', 'MTQ', 'MUS', 'MWI', 'MYS', 'MYT', 'NAM', 'NCL', 'NER', 'NFK', 'NGA', 'NIC', 'NIU', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OMN', 'PAK', 'PAN', 'PCN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PYF', 'QAT', 'REU', 'ROU', 'RUS', 'RWA', 'SAU', 'SDN', 'SEN', 'SGP', 'SGS', 'SHN', 'SJM', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SPM', 'SRB', 'SSD', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TGO', 'THA', 'TJK', 'TKL', 'TKM', 'TLS', 'TON', 'TTO', 'TUN', 'TUR', 'TUV', 'TWN', 'TZA', 'UGA', 'UKR', 'UMI', 'URY', 'USA', 'UZB', 'VAT', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLF', 'WOR', 'WSM', 'YEM', 'ZAF', 'ZMB', 'ZWE', name='providercarbonfootprintzone'), autoincrement=False, nullable=True),
    sa.Column('model_carbon_footprint_total_params', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_carbon_footprint_active_params', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_context_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vector_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('qos_metric', postgresql.ENUM('TTFT', 'LATENCY', 'INFLIGHT', 'PERFORMANCE', name='metrictype'), autoincrement=False, nullable=True),
    sa.Column('qos_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['router_id'], ['router.id'], name=op.f('router_provider_router_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('router_provider_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('router_provider_pkey')),
    sa.UniqueConstraint('url', 'model_name', name=op.f('unique_provider_url_model_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_router_provider_id'), 'router_provider', ['id'], unique=False)
    op.drop_index(op.f('ix_provider_id'), table_name='provider')
    op.drop_table('provider')
    # ### end Alembic commands ###
