"""change qos

Revision ID: ea462f747600
Revises: 208e1420dc3d
Create Date: 2025-10-28 23:58:16.296662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea462f747600'
down_revision: Union[str, None] = '208e1420dc3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the metrictype enum first
    metrictype = sa.Enum('TTFT', 'LATENCY', 'INFLIGHT', 'PERFORMANCE', name='metrictype')
    metrictype.create(op.get_bind(), checkfirst=True)
    
    op.add_column('router_provider', sa.Column('qos_metric', metrictype, nullable=True))
    op.add_column('router_provider', sa.Column('qos_value', sa.Float(), nullable=True))
    op.drop_column('router_provider', 'max_parallel_requests')
    op.drop_column('router_provider', 'qos_policy')
    op.drop_column('router_provider', 'performance_threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('router_provider', sa.Column('performance_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('router_provider', sa.Column('qos_policy', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('router_provider', sa.Column('max_parallel_requests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('router_provider', 'qos_value')
    op.drop_column('router_provider', 'qos_metric')
    
    # Drop the metrictype enum after removing the columns
    metrictype = sa.Enum('TTFT', 'LATENCY', 'INFLIGHT', 'PERFORMANCE', name='metrictype')
    metrictype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
