import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'category',
      label: 'Getting started',
      items: [
        'getting-started/quickstart',
        'getting-started/configuration_file',
        'getting-started/environment_variables',
      ],
    },
    {
        type: 'category',
        label: 'Guides',
        items: [
                'guides/chat_completions',
                'guides/rag',
                'guides/ocr',
                'guides/audio_transcriptions',
                'guides/models',
                'guides/IDE', // not generated from notebook
                ],
    },
    {
        type: 'category',
        label: 'Dependencies',
        items: [
                'dependencies/postgres',
                'dependencies/prometheus',
                'dependencies/redis',
                'dependencies/sentry',
                'dependencies/vector_store',
                ],
    },
    {
        type: 'category',
        label: 'Functionalities',
        items: [
                'functionalities/budget',
                'functionalities/environmental_footprint',
                {
                    type: 'category',
                    label: 'Identity and Access Management',
                    link: {
                        type: 'doc',
                        id: 'functionalities/iam/index',
                    },
                    items: [
                        'functionalities/iam/roles-permissions-rate-limitings',
                        'functionalities/iam/organizations-projects-users',
                        'functionalities/iam/api-keys',
                    ],
                },
                {
                    type: 'category',
                    label: 'Document Management',
                    link: {
                        type: 'doc',
                        id: 'functionalities/document-management/index',
                    },
                    items: [
                        'functionalities/document-management/collections',
                        'functionalities/document-management/parsing-and-chunking',
                        'functionalities/document-management/rag',
                    ],
                },
                'functionalities/usage',
                ],
    },
    {
      type: 'category',
      label: 'Models',
      items: ['models/models', 'models/routing'],
    },
    {
      type: 'category',
      label: 'Contributing',
      link: {
        type: 'doc',
        id: 'contributing/index',
      },
      items:  [
              'contributing/development-environment',
              'contributing/commit-hooks',
              'contributing/sql',
              'contributing/documentation',
              ],
    },
  ]
};

export default sidebars;
